# Generated by Django 3.0.4 on 2020-03-23 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0006_meeting_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='removed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
