# Generated by Django 3.0.4 on 2020-03-25 16:20

# Edited manually on 2023-03-06 to remove jsonfield references

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0008_attendee_safedelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='backend_metadata',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='backend_type',
            field=models.CharField(choices=[('bluejeans', 'BlueJeans')], max_length=20, null=True),
        ),
    ]
