# Generated by Django 3.0.4 on 2020-03-26 23:32

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0009_auto_20200325_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='backend_metadata',
            field=jsonfield.fields.JSONField(default=dict, null=True),
        ),
    ]
