# Generated by Django 3.0.5 on 2020-04-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0010_auto_20200326_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
