# Generated by Django 3.0.6 on 2020-05-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('officehours_api', '0014_meeting_agenda'), ('officehours_api', '0015_auto_20200515_0941')]

    dependencies = [
        ('officehours_api', '0013_add_queue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='agenda',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
