# Generated by Django 3.0.6 on 2020-05-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0014_meeting_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='agenda',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
