# Generated by Django 3.0.7 on 2020-06-04 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('officehours_api', '0015_profile_phone_number'), ('officehours_api', '0016_auto_20200528_1540'), ('officehours_api', '0017_auto_20200601_1058')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('officehours_api', '0014_meeting_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officehours_api.Profile'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(through='officehours_api.Attendee', to='officehours_api.Profile'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(through='officehours_api.Attendee', to=settings.AUTH_USER_MODEL),
        ),
    ]
