# Generated by Django 3.0.6 on 2020-05-28 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0015_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officehours_api.Profile'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(through='officehours_api.Attendee', to='officehours_api.Profile'),
        ),
    ]
