# Generated by Django 3.0.8 on 2020-08-04 14:12

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0017_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='backend_type',
            field=models.CharField(
                choices=[('inperson', 'InPerson'), ('bluejeans', 'BlueJeans')],
                default='bluejeans',
                max_length=20,
            ),
        ),
    ]
