# Generated by Django 3.0.8 on 2020-07-29 19:06

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0018_backend_type_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backend_metadata',
            field=jsonfield.fields.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='backend_type',
            field=models.CharField(choices=[('inperson', 'InPerson'), ('bluejeans', 'BlueJeans'), ('zoom', 'Zoom')], default='zoom', max_length=20),
        ),
    ]
