# Generated by Django 3.0.10 on 2020-10-13 19:39

import django.contrib.postgres.fields
from django.db import migrations, models
import officehours_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0018_backend_type_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='backend_type',
            field=models.CharField(choices=[['inperson', 'In Person'], ['bluejeans', 'BlueJeans']], default=officehours_api.models.get_default_backend, max_length=20),
        ),
        migrations.AlterField(
            model_name='queue',
            name='allowed_backends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[['inperson', 'In Person'], ['bluejeans', 'BlueJeans']], max_length=20), default=officehours_api.models.get_default_allowed_backends, size=None),
        ),
    ]
