# Generated by Django 3.0.8 on 2020-08-05 18:58

import django.contrib.postgres.fields
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0018_backend_type_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backend_metadata',
            field=jsonfield.fields.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='backend_type',
            field=models.CharField(choices=[('zoom', 'Zoom'), ('bluejeans', 'BlueJeans'), ('inperson', 'InPerson')], default='zoom', max_length=20),
        ),
        migrations.AlterField(
            model_name='queue',
            name='allowed_backends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('zoom', 'Zoom'), ('bluejeans', 'BlueJeans'), ('inperson', 'InPerson')], max_length=20), default=['zoom'], size=2),
        ),
    ]
