# Generated by Django 3.0.10 on 2020-10-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0019_auto_20201013_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_me_attendee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='notify_me_host',
            field=models.BooleanField(default=False),
        ),
    ]
