# Generated by Django 3.0.10 on 2020-11-05 18:53

# Edited manually on 2023-03-06 to remove jsonfield references

from django.db import migrations, models
import officehours_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0020_auto_20201013_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backend_metadata',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='backend_type',
            field=models.CharField(
                choices=[('bluejeans', 'BlueJeans'), ('inperson', 'In Person'), ('zoom', 'Zoom')],
                default=officehours_api.models.get_default_backend,
                max_length=20
            ),
        ),
        # Removed allowed_backends ArrayField — not supported in SQLite
    ]
