# Generated by Django 3.0.10 on 2020-11-05 18:53

import django.contrib.postgres.fields
from django.db import migrations, models
import jsonfield.fields
import officehours_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0020_auto_20201013_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backend_metadata',
            field=jsonfield.fields.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='backend_type',
            field=models.CharField(choices=[['bluejeans', 'BlueJeans'], ['inperson', 'In Person'], ['zoom', 'Zoom']], default=officehours_api.models.get_default_backend, max_length=20),
        ),
        migrations.AlterField(
            model_name='queue',
            name='allowed_backends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[['bluejeans', 'BlueJeans'], ['inperson', 'In Person'], ['zoom', 'Zoom']], max_length=20), default=officehours_api.models.get_default_allowed_backends, size=None),
        ),
    ]
