# Generated by Django 3.0.14 on 2021-04-25 17:30

import django.contrib.postgres.fields
from django.db import migrations, models
import officehours_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0021_auto_20201105_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='meeting_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='backend_type',
            field=models.CharField(choices=[['bluejeans', 'BlueJeans'], ['zoom', 'Zoom'], ['inperson', 'In Person']], default=officehours_api.models.get_default_backend, max_length=20),
        ),
        migrations.AlterField(
            model_name='queue',
            name='allowed_backends',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[['bluejeans', 'BlueJeans'], ['zoom', 'Zoom'], ['inperson', 'In Person']], max_length=20), default=officehours_api.models.get_default_allowed_backends, size=None),
        ),
    ]
