# Generated by Django 3.0.14 on 2021-04-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0021_auto_20201105_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='physLocation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
