# Generated by Django 3.2.18 on 2023-04-11 07:02

# Edited manually on 2023-04-14 to remove jsonfield references

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0022_auto_20210428_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='backend_metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
