# Generated by Django 4.2.18 on 2025-01-23 21:14

import django.contrib.postgres.fields
from django.db import migrations, models
import officehours_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0027_auto_20240703_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='backend_type',
            field=models.CharField(default=officehours_api.models.get_default_backend, max_length=20),
        ),
        #migrations.AlterField(
         #   model_name='queue',
          #  name='allowed_backends',
           # field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=officehours_api.models.get_default_allowed_backends, size=None),
        #),
    ]
