# Generated by Django 4.2 on 2024-10-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0027_auto_20240703_1137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingStartLogsView',
        ),
    ]
