# Generated by Django 4.2.18 on 2025-05-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0028_alter_meeting_backend_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number_status',
            field=models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid'), ('NEEDS_VERIFICATION', 'Needs Verification')], default='VALID', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='twilio_error_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='twilio_error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
