# Generated by Django 4.2.18 on 2025-05-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0029_profile_phone_number_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number_status',
            field=models.CharField(choices=[('VALID', 'Valid'), ('INVALID', 'Invalid'), ('NEEDS_VERIFICATION', 'Needs Verification')], default='NEEDS_VERIFICATION', max_length=20),
        ),
    ]
