# Generated by Django 4.2.18 on 2025-06-07 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0030_queueannouncement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueannouncement',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
