# Generated by Django 4.2.18 on 2025-08-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officehours_api', '0031_update_announcement_timestamp'),
        ('officehours_api', '0030_update_simpler_meeting_start_logs_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_me_announcement',
            field=models.BooleanField(default=False),
        ),
    ]
