# Generated by Django 3.0.4 on 2020-03-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluejeans_queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluejeansmeeting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
