# Generated by Django 3.0.4 on 2020-03-17 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bluejeans_queue', '0002_bluejeansmeeting_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluejeansmeeting',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bluejeans_attendee', to=settings.AUTH_USER_MODEL),
        ),
    ]
