apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  labels:
    app: web
spec:
  tls:
  - hosts:
    - dev.officehours.it.umich.edu
    - www.dev.officehours.it.umich.edu
    secretName: web-tls
  rules:
  - host: dev.officehours.it.umich.edu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 80
  - host: www.dev.officehours.it.umich.edu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 80
