apiVersion: v1
kind: DeploymentConfig
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    app: web
    org: umich
    project: officehours
    variant: dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
        org: umich
        project: officehours
        variant: dev
    spec:
      containers:
      - name: web
        image: docker-registry.default.svc:5000/officehours-dev/officehours:latest
        command: ["/usr/src/app/docker-entrypoint.sh", "python", "manage.py", "runserver"]
        args: ["0.0.0.0:8001"]
        ports:
        - containerPort: 8001
        envFrom:
        - secretRef:
            name: secrets
  triggers:
  - type: "ImageChange"
    imageChangeParams:
      automatic: true
      from:
        kind: "ImageStreamTag"
        name: "officehours:latest"
        namespace: "officehours-dev"
      containerNames:
      - "web"