apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web
spec:
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    name: officehours-web-dev
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
